[package]
name = "repub"
version = "0.1.0"
edition = "2021"
description = "Rust library and binary for converting mhtml webpages into summarized epubs"
repository = "https://github.com/erikbrinkman/repub-rs"
license = "MIT"
keywords = ["mhtml", "epub", "remarkable"]

[dependencies]
clap = { version = "4.0.32", features = ["wrap_help", "derive"], optional = true }
epub-builder = { git = "https://github.com/lise-henry/epub-builder/", version = "0.6.0", rev = "5aebf8ad3980237e2762cac30ceda8730834afa2", default-features = false, features = ["zip-library"] }
eyre = "0.6.8"
image = "0.24.5"
kuchiki = "0.8.1"
mail-parser = "0.8.0"
markup5ever = "0.10.1"
percent-encoding = "2.2.0"
readable-readability = "0.4.0"
strsim = "0.10.0"

[dev-dependencies]
base64 = "0.20.0"
epub = "2.0.0"
quoted_printable = "0.4.6"

[features]
binary = ["clap"]

[lib]
name = "repub"

[[bin]]
name = "repub"
required-features = ["binary"]
